# Generated by Django 5.1.6 on 2025-03-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate'), ('conference', 'Conference'), ('concert', 'Concert'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('venue_type', models.CharField(choices=[('banquet hall', 'Banquet Hall'), ('conference center', 'Conference Center'), ('hotels/resorts', 'Hotels/Resorts'), ('restaurant', 'Restaurant'), ('outdoor spaces', 'Outdoor Spaces')], max_length=30)),
                ('attendees', models.PositiveIntegerField()),
                ('theme', models.CharField(max_length=100)),
            ],
        ),
    ]
