# Generated by Django 5.1.6 on 2025-03-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0002_chatbotinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
